#!/bin/bash

# Hide "last login" line when starting a new terminal session
touch $HOME/.hushlogin

# Install zsh
echo 'Install oh-my-zsh'
echo '-----------------'
rm -rf $HOME/.oh-my-zsh
curl -L https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh


DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Add global gitignore
ln -sf $DOTFILES/git/gitconfig $HOME/.gitconfig
ln -sf $DOTFILES/git/.global-gitignore $HOME/.gitignore_global


# Symlink zsh prefs
rm $HOME/.zshrc
ln -s $DOTFILES/shell/.zshrc $HOME/.zshrc

# Symlink yarn prefs
rm $HOME/.yarnrc
ln -s $DOTFILES/shell/.yarnrc $HOME/.yarnrc

# Fix missing font characters (see https://github.com/robbyrussell/oh-my-zsh/issues/1906)
cd ~/.oh-my-zsh/themes/
git checkout d6a36b1 agnoster.zsh-theme

# Activate z
cd ~/.dotfiles/zsh
chmod +x z.sh

echo 'Install homebrew'
echo '----------------'
echo install homebrew
sudo rm -rf /usr/local/Cellar /usr/local/.git && brew cleanup
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
echo 'Run the brew file!'
echo 'composer global require laravel/valet'

echo '++++++++++++++++++++++++++++++'
echo 'Things to do to make the agnoster terminal theme work:'
echo '1. Install menlo patched font included in ~/.dotfiles/misc https://gist.github.com/qrush/1595572/raw/Menlo-Powerline.otf'
echo '2. Install patched solarized theme included in ~/.dotfiles/misc'

echo '++++++++++++++++++++++++++++++'
echo 'Some optional tidbits'

echo '1. Set some sensible os x defaults by running: $DOTFILES/macos/set-defaults.sh'

echo '++++++++++++++++++++++++++++++'
echo '++++++++++++++++++++++++++++++'
